### ISSUE TITLE
Advertisements with Google Adsense

### ISSUE THREAD

**Issue by omarchehab98** [SentiSocial/sentisocial-frontend#2]
- [ ] Finish the Google Adsense account signup when the site is pushed live.
- [ ] Create an **AdvertisementCard** Class that displays an advertisement.
Should look something like this
```html
<div class="advertisement">
    <div class="advertisement--space">...</div>
    <hr class="advertisement--seperator">
    <p class="advertisement--indicator">Advertisement</p>
</div>
```
`.advertisement--space` style
```css
text-align: center;
```
`.advertisement--seperator` style
```css
margin: 10px 0;
```
`.advertisement--indicator` style
```css
text-align: center;
color: #aaaaaa;
margin: 0;
```

- [ ] Show an **AdvertisementCard** once every `X` number of content cards.

![Advertisement Layout](https://cloud.githubusercontent.com/assets/12089120/22848343/b83577ec-efc1-11e6-9bcc-e0afeb9ad805.png)
This is a mockup.

**Comment by GunshipPenguin** [comment]
@omarchehab98 This should come after the API related changes are finished,
