### ISSUE TITLE
Tweets do not show up in Private Browsing mode when using Firefox

### ISSUE THREAD

**Issue by GunshipPenguin** [SentiSocial/sentisocial-frontend#33]
Using Firefox 45.7.0 ESR in private browsing mode causes tweets to not show up. Requests to Twitter for the tweets do not seem to be being made.

**Comment by omarchehab98** [comment]
@GunshipPenguin we should look into methods of identifying if a browser has Tracking Protection and display a message instead of the Tweet.

**Comment by omarchehab98** [comment]
6f747089f2c5036792581131eebc7e8a019c73f7
