### ISSUE TITLE
Usabilty Enhancements

### ISSUE THREAD

**Issue by DennisTDev** [SentiSocial/sentisocial-frontend#37]
- [ ] Site should return the user to where they were previously browsing upon clicking on a trend and then pressing the back button.

- [x] Chart scrolling (swiping on mobile)

**Comment by omarchehab98** [comment]
Chart scrolling is now fixed! :)
f5153aa59c3ca6c4933e9159ad0591ddc61a818b

**Comment by omarchehab98** [comment]
> - [ ] Site should return the user to where they were previously browsing upon clicking on a trend and then pressing the back button.

This issue can be fixed by having an Application wide state. We should to use [`reactjs/redux`](https://github.com/reactjs/redux) or [`mobxjs/mobx`](https://github.com/mobxjs/mobx)

**Comment by omarchehab98** [comment]
We began using redux in the new update.
